/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

import type { ArchiveBlock, Form, FormBlock, FormSubmission, MediaBlock, PayloadJob, PayloadKv, PayloadLockedDocument, PayloadMigration, PayloadPreference, Redirect, Search } from './payload-types-b'
import type { CategoriesSelect, CollectionsWidget, Footer, FooterSelect, FormSubmissionsSelect, FormsSelect, Header, HeaderSelect, MediaSelect, PagesSelect, PayloadFoldersSelect, PayloadJobsSelect, PayloadKvSelect, PayloadLockedDocumentsSelect, PayloadMigrationsSelect, PayloadPreferencesSelect, PostsSelect, RedirectsSelect, SearchSelect, TaskSchedulePublish, UsersSelect } from './payload-types-c'

export type SupportedTimezones =
  | 'Pacific/Midway' | 'Pacific/Niue' | 'Pacific/Honolulu' | 'Pacific/Rarotonga'
  | 'America/Anchorage' | 'Pacific/Gambier' | 'America/Los_Angeles' | 'America/Tijuana'
  | 'America/Denver' | 'America/Phoenix' | 'America/Chicago' | 'America/Guatemala'
  | 'America/New_York' | 'America/Bogota' | 'America/Caracas' | 'America/Santiago'
  | 'America/Buenos_Aires' | 'America/Sao_Paulo' | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores' | 'Atlantic/Cape_Verde' | 'Europe/London' | 'Europe/Berlin'
  | 'Africa/Lagos' | 'Europe/Athens' | 'Africa/Cairo' | 'Europe/Moscow'
  | 'Asia/Riyadh' | 'Asia/Dubai' | 'Asia/Baku' | 'Asia/Karachi' | 'Asia/Tashkent'
  | 'Asia/Calcutta' | 'Asia/Dhaka' | 'Asia/Almaty' | 'Asia/Jakarta' | 'Asia/Bangkok'
  | 'Asia/Shanghai' | 'Asia/Singapore' | 'Asia/Tokyo' | 'Asia/Seoul'
  | 'Australia/Brisbane' | 'Australia/Sydney' | 'Pacific/Guam' | 'Pacific/Noumea'
  | 'Pacific/Auckland' | 'Pacific/Fiji';

export interface Config {
  auth: { users: UserAuthOperations };
  blocks: {};
  collections: {
    pages: Page; posts: Post; media: Media; categories: Category; users: User;
    redirects: Redirect; forms: Form; 'form-submissions': FormSubmission; search: Search;
    'payload-kv': PayloadKv; 'payload-jobs': PayloadJob; 'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument; 'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: { 'payload-folders': { documentsAndFolders: 'payload-folders' | 'media' } };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: { defaultIDType: number };
  fallbackLocale: null;
  globals: { header: Header; footer: Footer };
  globalsSelect: { header: HeaderSelect<false> | HeaderSelect<true>; footer: FooterSelect<false> | FooterSelect<true> };
  locale: null;
  widgets: { collections: CollectionsWidget };
  user: User;
  jobs: { tasks: { schedulePublish: TaskSchedulePublish; inline: { input: unknown; output: unknown } }; workflows: unknown };
}
export interface UserAuthOperations {
  forgotPassword: { email: string; password: string };
  login: { email: string; password: string };
  registerFirstUser: { email: string; password: string };
  unlock: { email: string; password: string };
}
export interface Page {
  id: number; title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: { root: { type: string; children: { type: any; version: number; [k: string]: unknown }[]; direction: ('ltr' | 'rtl') | null; format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''; indent: number; version: number }; [k: string]: unknown } | null;
    links?: { link: { type?: ('reference' | 'custom') | null; newTab?: boolean | null; reference?: ({ relationTo: 'pages'; value: number | Page } | null) | ({ relationTo: 'posts'; value: number | Post } | null); url?: string | null; label: string; appearance?: ('default' | 'outline') | null }; id?: string | null }[] | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: { title?: string | null; image?: (number | null) | Media; description?: string | null };
  publishedAt?: string | null; generateSlug?: boolean | null; slug: string; updatedAt: string; createdAt: string; _status?: ('draft' | 'published') | null;
}
export interface Post {
  id: number; title: string; heroImage?: (number | null) | Media;
  content: { root: { type: string; children: { type: any; version: number; [k: string]: unknown }[]; direction: ('ltr' | 'rtl') | null; format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''; indent: number; version: number }; [k: string]: unknown };
  relatedPosts?: (number | Post)[] | null; categories?: (number | Category)[] | null;
  meta?: { title?: string | null; image?: (number | null) | Media; description?: string | null };
  publishedAt?: string | null; authors?: (number | User)[] | null;
  populatedAuthors?: { id?: string | null; name?: string | null }[] | null;
  generateSlug?: boolean | null; slug: string; updatedAt: string; createdAt: string; _status?: ('draft' | 'published') | null;
}
export interface Media {
  id: number; alt?: string | null;
  caption?: { root: { type: string; children: { type: any; version: number; [k: string]: unknown }[]; direction: ('ltr' | 'rtl') | null; format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''; indent: number; version: number }; [k: string]: unknown } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string; createdAt: string; url?: string | null; thumbnailURL?: string | null; filename?: string | null; mimeType?: string | null; filesize?: number | null; width?: number | null; height?: number | null; focalX?: number | null; focalY?: number | null;
  sizes?: {
    thumbnail?: { url?: string | null; width?: number | null; height?: number | null; mimeType?: string | null; filesize?: number | null; filename?: string | null };
    square?: { url?: string | null; width?: number | null; height?: number | null; mimeType?: string | null; filesize?: number | null; filename?: string | null };
    small?: { url?: string | null; width?: number | null; height?: number | null; mimeType?: string | null; filesize?: number | null; filename?: string | null };
    medium?: { url?: string | null; width?: number | null; height?: number | null; mimeType?: string | null; filesize?: number | null; filename?: string | null };
    large?: { url?: string | null; width?: number | null; height?: number | null; mimeType?: string | null; filesize?: number | null; filename?: string | null };
    xlarge?: { url?: string | null; width?: number | null; height?: number | null; mimeType?: string | null; filesize?: number | null; filename?: string | null };
    og?: { url?: string | null; width?: number | null; height?: number | null; mimeType?: string | null; filesize?: number | null; filename?: string | null };
  };
}
export interface FolderInterface {
  id: number; name: string; folder?: (number | null) | FolderInterface;
  documentsAndFolders?: { docs?: ({ relationTo?: 'payload-folders'; value: number | FolderInterface } | { relationTo?: 'media'; value: number | Media })[]; hasNextPage?: boolean; totalDocs?: number };
  folderType?: 'media'[] | null; updatedAt: string; createdAt: string;
}
export interface Category {
  id: number; title: string; generateSlug?: boolean | null; slug: string; parent?: (number | null) | Category;
  breadcrumbs?: { doc?: (number | null) | Category; url?: string | null; label?: string | null; id?: string | null }[] | null;
  updatedAt: string; createdAt: string;
}
export interface User {
  id: number; name?: string | null; updatedAt: string; createdAt: string; email: string;
  resetPasswordToken?: string | null; resetPasswordExpiration?: string | null; salt?: string | null; hash?: string | null;
  loginAttempts?: number | null; lockUntil?: string | null;
  sessions?: { id: string; createdAt?: string | null; expiresAt: string }[] | null;
  password?: string | null; collection: 'users';
}
export interface CallToActionBlock {
  richText?: { root: { type: string; children: { type: any; version: number; [k: string]: unknown }[]; direction: ('ltr' | 'rtl') | null; format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''; indent: number; version: number }; [k: string]: unknown } | null;
  links?: { link: { type?: ('reference' | 'custom') | null; newTab?: boolean | null; reference?: ({ relationTo: 'pages'; value: number | Page } | null) | ({ relationTo: 'posts'; value: number | Post } | null); url?: string | null; label: string; appearance?: ('default' | 'outline') | null }; id?: string | null }[] | null;
  id?: string | null; blockName?: string | null; blockType: 'cta';
}
export interface ContentBlock {
  columns?: { size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null; richText?: { root: { type: string; children: { type: any; version: number; [k: string]: unknown }[]; direction: ('ltr' | 'rtl') | null; format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''; indent: number; version: number }; [k: string]: unknown } | null; enableLink?: boolean | null; link?: { type?: ('reference' | 'custom') | null; newTab?: boolean | null; reference?: ({ relationTo: 'pages'; value: number | Page } | null) | ({ relationTo: 'posts'; value: number | Post } | null); url?: string | null; label: string; appearance?: ('default' | 'outline') | null }; id?: string | null }[] | null;
  id?: string | null; blockName?: string | null; blockType: 'content';
}
