/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect\u003cfalse\u003e | PagesSelect\u003ctrue\u003e;
    posts: PostsSelect\u003cfalse\u003e | PostsSelect\u003ctrue\u003e;
    media: MediaSelect\u003cfalse\u003e | MediaSelect\u003ctrue\u003e;
    categories: CategoriesSelect\u003cfalse\u003e | CategoriesSelect\u003ctrue\u003e;
    users: UsersSelect\u003cfalse\u003e | UsersSelect\u003ctrue\u003e;
    redirects: RedirectsSelect\u003cfalse\u003e | RedirectsSelect\u003ctrue\u003e;
    forms: FormsSelect\u003cfalse\u003e | FormsSelect\u003ctrue\u003e;
    'form-submissions': FormSubmissionsSelect\u003cfalse\u003e | FormSubmissionsSelect\u003ctrue\u003e;
    search: SearchSelect\u003cfalse\u003e | SearchSelect\u003ctrue\u003e;
    'payload-kv': PayloadKvSelect\u003cfalse\u003e | PayloadKvSelect\u003ctrue\u003e;
    'payload-jobs': PayloadJobsSelect\u003cfalse\u003e | PayloadJobsSelect\u003ctrue\u003e;
    'payload-folders': PayloadFoldersSelect\u003cfalse\u003e | PayloadFoldersSelect\u003ctrue\u003e;
    'payload-locked-documents': PayloadLockedDocumentsSelect\u003cfalse\u003e | PayloadLockedDocumentsSelect\u003ctrue\u003e;
    'payload-preferences': PayloadPreferencesSelect\u003cfalse\u003e | PayloadPreferencesSelect\u003ctrue\u003e;
    'payload-migrations': PayloadMigrationsSelect\u003cfalse\u003e | PayloadMigrationsSelect\u003ctrue\u003e;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect\u003cfalse\u003e | HeaderSelect\u003ctrue\u003e;
    footer: FooterSelect\u003cfalse\u003e | FooterSelect\u003ctrue\u003e;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
